//! Enumeration of errors the tool can produce.

use std::io;
use std::io::ErrorKind;
use thiserror::Error;

/// Enumeration of errors generated by the tool
#[derive(Debug, Error)]
pub enum ToolError {
    /// Indicates something went wrong with the opening the file.
    #[error("Error reading a file. IO Error Kind: {kind}, path: {filepath}")]
    FileReadError { kind: ErrorKind, filepath: String },

    /// Indicates something went wrong copying file contents into the hasher
    #[error("Error read file bytes into hasher")]
    ByteCopyError(#[from] io::Error),
}
