/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0. If a copy of the MPL was not distributed with this
* file, You can obtain one at https: //mozilla.org/MPL/2.0/.
*/
//! Enumeration of errors the tool can produce.

use std::io;
use std::io::ErrorKind;
use std::path::StripPrefixError;
use thiserror::Error;

/// Enumeration of errors generated by the tool
#[derive(Debug, Error)]
pub enum ToolError {
    /// Indicates something went wrong with the opening the file.
    #[error("Error reading a file. IO Error Kind: {kind}, path: {filepath}")]
    FileReadError {
        /// The kind of the source error
        kind: ErrorKind,
        /// The filepath that triggered the error.
        filepath: String,
    },

    /// Indicates something went wrong copying file contents into the hasher
    #[error("Error reading file bytes into hasher")]
    ByteCopyError(#[from] io::Error),

    /// Indicates an error unwrapping a path
    #[error("Error stripping a path")]
    StripPrefixError(#[from] StripPrefixError),
}
