name: Build and Test Rust

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:

  build_and_test:
    name: Build and Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        profile: [dev, release]


    steps:
    - uses: actions/checkout@v5
    - name: Build
      run: cargo build --verbose --profile ${{ matrix.profile }} --tests

    - name: Run tests
      run: cargo test --verbose --profile ${{ matrix.profile }}
